// Package filesvcclient provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package filesvcclient

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for V1ErrorCode.
const (
	N400 V1ErrorCode = 400
	N401 V1ErrorCode = 401
	N403 V1ErrorCode = 403
	N404 V1ErrorCode = 404
	N408 V1ErrorCode = 408
	N409 V1ErrorCode = 409
	N413 V1ErrorCode = 413
	N500 V1ErrorCode = 500
	N501 V1ErrorCode = 501
)

// Defines values for V1ErrorType.
const (
	ALREADYEXISTS      V1ErrorType = "ALREADY_EXISTS"
	CONTENTTOOLARGE    V1ErrorType = "CONTENT_TOO_LARGE"
	FAILEDPRECONDITION V1ErrorType = "FAILED_PRECONDITION"
	INTERNAL           V1ErrorType = "INTERNAL"
	INVALIDARGUMENT    V1ErrorType = "INVALID_ARGUMENT"
	NOTFOUND           V1ErrorType = "NOT_FOUND"
	OUTOFRANGE         V1ErrorType = "OUT_OF_RANGE"
	PERMISSIONDENIED   V1ErrorType = "PERMISSION_DENIED"
	REQUESTTIMEOUT     V1ErrorType = "REQUEST_TIMEOUT"
	UNAUTHENTICATED    V1ErrorType = "UNAUTHENTICATED"
	UNIMPLEMENTED      V1ErrorType = "UNIMPLEMENTED"
)

// V1Error defines model for v1Error.
type V1Error struct {
	Code V1ErrorCode `json:"code"`

	// Details list of nested errors if applicable
	Details *[]V1Error  `json:"details,omitempty"`
	Message string      `json:"message"`
	Type    V1ErrorType `json:"type"`
}

// V1ErrorCode defines model for V1Error.Code.
type V1ErrorCode int32

// V1ErrorType defines model for v1ErrorType.
type V1ErrorType string

// V1ImageSplitRequest defines model for v1ImageSplitRequest.
type V1ImageSplitRequest struct {
	// Dpi Rasterization DPI.
	Dpi *int `json:"dpi,omitempty"`

	// File PDF file (application/pdf)
	File openapi_types.File `json:"file"`

	// Pages Page selection like "1-3,5". Omit for all pages.
	Pages *string `json:"pages,omitempty"`
}

// V1ZipArchive A ZIP file containing the outputs.
type V1ZipArchive = openapi_types.File

// V1BadRequestError defines model for v1BadRequestError.
type V1BadRequestError = V1Error

// V1PayloadTooLargeError defines model for v1PayloadTooLargeError.
type V1PayloadTooLargeError = V1Error

// V1UnprocessableEntityError defines model for v1UnprocessableEntityError.
type V1UnprocessableEntityError = V1Error

// SplitToImagesMultipartRequestBody defines body for SplitToImages for multipart/form-data ContentType.
type SplitToImagesMultipartRequestBody = V1ImageSplitRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// SplitToImagesWithBody request with any body
	SplitToImagesWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) SplitToImagesWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSplitToImagesRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewSplitToImagesRequestWithBody generates requests for SplitToImages with any type of body
func NewSplitToImagesRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/pdf/split/images")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// SplitToImagesWithBodyWithResponse request with any body
	SplitToImagesWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SplitToImagesResponse, error)
}

type SplitToImagesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *V1BadRequestError
	JSON413      *V1PayloadTooLargeError
	JSON422      *V1UnprocessableEntityError
}

// Status returns HTTPResponse.Status
func (r SplitToImagesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SplitToImagesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// SplitToImagesWithBodyWithResponse request with arbitrary body returning *SplitToImagesResponse
func (c *ClientWithResponses) SplitToImagesWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SplitToImagesResponse, error) {
	rsp, err := c.SplitToImagesWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSplitToImagesResponse(rsp)
}

// ParseSplitToImagesResponse parses an HTTP response from a SplitToImagesWithResponse call
func ParseSplitToImagesResponse(rsp *http.Response) (*SplitToImagesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SplitToImagesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest V1BadRequestError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 413:
		var dest V1PayloadTooLargeError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON413 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest V1UnprocessableEntityError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}
